### ISSUE TITLE
CLATCH OpenCV version?

### ISSUE THREAD

**Issue by willard-yuan** [komrad36/CLATCH#2]
Hi @komrad36 

There is a problem when I compiled the CLATCH. The error is caused by the following:

```cpp
cv::Ptr<cv::ORB> orb = cv::ORB::create(numkps, 1.2f, 8, 31, 0, 2, cv::ORB::HARRIS_SCORE, 31, 20);
```

Would you like to tell me which OpenCV version you use to compile the CLATCH?

**Comment by komrad36** [comment]
Hi,

OpenCV 3. If you still have trouble, share more details about the error you
receive.

Thanks,
Kareem

**Comment by willard-yuan** [comment]
Thank you for your fast reply. My development environment is based on OpenCV 2.X. Is't possible to replace ORB in OpenCV 3 with  ORB in OpenCV 2.X?

**Comment by komrad36** [comment]
Sure. CLATCH is not dependent on OpenCV at all. The intent of lots of my
work is to improve on OpenCV or the status quo in general. In the CLATCH
project I just use it as an easy way to obtain keypoints. You can replace
that with any other desired method of obtaining them, including OpenCV 2,
my stuff (KFAST and FeatureAngle), or any other method.
